---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: demo-helm-release-bb-app
  namespace: flux-system
spec:
  chart:
    spec:
      chart: block-buster-helm-app
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: demo-source-helm-bb-app
  interval: 10s
  targetNamespace: bb-demo
  values:
    labels:
      app:
        env: dev
        name: block-buster
        version: 7.6.0
    namespace:
      name: bb-demo
    replicaCount: 5
    service:
      nodePort: 30006
      type: NodePort
